# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               bv的孤岛
tagline:             'Just my random gibberish'
description:         '随便写写'
url:                 https://psyclaudez.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Bowei Zhang
  #url:               https://twitter.com/mdo
  #email:             markdotto@gmail.com

# Custom vars
# version:             1.0.0

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
